### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by dev-bello** [devangspsingh/attendworkapp#1]
Hello dev, I'm stuck and i want to ask you for help if you're willing to offer one. Thanks

**Comment by devangspsingh** [comment]
How can i help you ?

**Comment by dev-bello** [comment]
Is there any platform you are where I could message you and list them for you?

**Comment by devangspsingh** [comment]
you can connect with me on LinkedIn


[https://www.linkedin.com/in/devangspsingh/](url)

**Comment by dev-bello** [comment]
Done that since and still haven't connected
